# Generated by Django 4.2.7 on 2025-08-14 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retraite',
            fields=[
                ('num_secu', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_num_secu', message='Le numéro de sécurité sociale doit contenir 8 chiffres', regex='^[0-9]{8}$')], verbose_name='Numéro de Sécurité Sociale')),
                ('nom_agence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom Agence')),
                ('qualite_personne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qualité Personne')),
                ('id_num_personne', models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="L'ID personne doit contenir entre 5 et 6 chiffres", regex='^[0-9]{5,6}$')], verbose_name='ID Numéro Personne')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(default='Non spécifié', max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('mois_rattachement', models.CharField(max_length=7, verbose_name='Mois de Rattachement')),
                ('pension_cnss', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pension CNSS')),
                ('pension_cimr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pension CIMR')),
                ('montant_cmss_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant CMSS Mensuel')),
                ('part_patronale_cmss_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Part Patronale CMSS Mensuel')),
                ('montant_cmss_trimestriel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant CMSS Trimestriel')),
                ('montant_cmcas_trimestriel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant CMCAS Trimestriel')),
            ],
            options={
                'verbose_name': 'Gestion Retraite',
                'verbose_name_plural': 'Gestion des Retraites',
                'db_table': 'gestion_retraite',
            },
        ),
        migrations.CreateModel(
            name='TM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_tm', models.DateField(verbose_name='Date du TM')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retraite', models.ForeignKey(db_column='retraite_num_secu', on_delete=django.db.models.deletion.CASCADE, related_name='tms', to='gestion.retraite')),
            ],
            options={
                'db_table': 'gestion_tm',
                'ordering': ['-date_tm'],
            },
        ),
        migrations.CreateModel(
            name='Cotisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('cotisation_cmss_trimestrielle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotisation_cmcas_trimestrielle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_banque', models.FileField(blank=True, null=True, upload_to='banque_uploads/')),
                ('retraite', models.ForeignKey(db_column='num_secu', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion.retraite')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='Arriere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_arriere', models.DateField(verbose_name="Date de l'arriéré")),
                ('type_arriere', models.CharField(choices=[('CMSS', 'CMSS'), ('CMCAS', 'CMCAS'), ('LES_DEUX', 'Les deux')], max_length=20, verbose_name='Type')),
                ('nombre_de_mois', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de mois')),
                ('montant_cmss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant CMSS')),
                ('montant_cmcas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant CMCAS')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retraite', models.ForeignKey(db_column='retraite_num_secu', on_delete=django.db.models.deletion.CASCADE, related_name='arrieres', to='gestion.retraite')),
            ],
            options={
                'db_table': 'gestion_arrieres',
                'ordering': ['-date_arriere'],
            },
        ),
    ]
