# Generated by Django 4.2.7 on 2025-08-18 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_piece', models.IntegerField(verbose_name='Numéro de pièce')),
                ('Montant_en_devise_interne', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en devise interne')),
                ('Texte', models.CharField(max_length=255, verbose_name='Description')),
                ('date_piece', models.DateField(verbose_name='Date de la pièce')),
            ],
            options={
                'verbose_name': 'Opération bancaire',
                'verbose_name_plural': 'Opérations bancaires',
                'ordering': ['-date_piece', 'N_piece'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField(auto_now_add=True, verbose_name='Date de calcul')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la cotisation', max_digits=10, verbose_name='Montant cotisation')),
                ('montant_cmss_trimestriel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant CMSS trimestriel')),
                ('montant_cmcas_trimestriel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant CMCAS trimestriel')),
                ('trimestre_de_remboursement', models.CharField(max_length=50, verbose_name='Trimestre de remboursement')),
                ('detail_ecart', models.TextField(blank=True, null=True, verbose_name='Détail des écarts')),
                ('operation_bancaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations', to='gestion.banque', verbose_name='Opération bancaire liée')),
                ('retraite', models.ForeignKey(db_column='num_secu', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion.retraite')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.DeleteModel(
            name='Cotisations',
        ),
    ]
