# Generated by Django 4.2.7 on 2025-08-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_banque_cotisation_delete_cotisations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'ordering': ['-date_de_saisie'], 'verbose_name': 'Cotisation', 'verbose_name_plural': 'Cotisations'},
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='date_calcul',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_de_saisie',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de saisie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='mois_rattachement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_mois', to='gestion.retraite', verbose_name='Mois de rattachement'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='retraite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion.retraite', verbose_name='Retraité'),
        ),
    ]
