# Generated by Django 4.2.7 on 2025-08-18 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_cotisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='Texte',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='mois_rattachement',
            field=models.CharField(default='01-2023', help_text='Format: MM-YYYY', max_length=7, verbose_name='Mois de rattachement'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cotisation'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant_cmcas_trimestriel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant CMCAS trimestriel'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant_cmss_trimestriel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant CMSS trimestriel'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='trimestre_de_remboursement',
            field=models.CharField(help_text='Format: Tn-YYYY (ex: T1-2023)', max_length=50, verbose_name='Trimestre de remboursement'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['retraite', 'trimestre_de_remboursement'], name='gestion_cot_retrait_f6bd82_idx'),
        ),
        migrations.AddConstraint(
            model_name='banque',
            constraint=models.UniqueConstraint(fields=('N_piece', 'date_piece'), name='unique_piece_date'),
        ),
    ]
