# Generated by Django 4.2.7 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_banque_texte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='mois_rattachement',
            field=models.CharField(help_text='Format: MM-YYYY', max_length=7, verbose_name='Mois de rattachement'),
        ),
    ]
