# Generated by Django 4.2.7 on 2025-08-18 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_cotisation_mois_rattachement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={'ordering': ['-date_piece', 'N_piece'], 'verbose_name': 'Banque', 'verbose_name_plural': 'Banques'},
        ),
        migrations.RemoveConstraint(
            model_name='banque',
            name='unique_piece_date',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='mois_rattachement',
        ),
        migrations.AlterField(
            model_name='banque',
            name='N_piece',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='operation_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations', to='gestion.banque', verbose_name='Opération bancaire'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='trimestre_de_remboursement',
            field=models.CharField(max_length=50, verbose_name='Trimestre de remboursement'),
        ),
        migrations.AddConstraint(
            model_name='banque',
            constraint=models.UniqueConstraint(fields=('N_piece', 'date_piece'), name='unique_piece_date_banque'),
        ),
    ]
