# Generated by Django 4.2.7 on 2025-08-18 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_banque_options_remove_banque_unique_piece_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cotisation',
            options={'ordering': ['-operation_bancaire__date_piece'], 'verbose_name': 'Cotisation', 'verbose_name_plural': 'Cotisations'},
        ),
        migrations.RemoveConstraint(
            model_name='banque',
            name='unique_piece_date_banque',
        ),
        migrations.RemoveIndex(
            model_name='cotisation',
            name='gestion_cot_retrait_f6bd82_idx',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='date_de_saisie',
        ),
        migrations.AlterField(
            model_name='banque',
            name='Montant_en_devise_interne',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='banque',
            name='date_piece',
            field=models.DateField(verbose_name='Date pièce'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='banque',
            constraint=models.UniqueConstraint(fields=('N_piece', 'date_piece'), name='banque_unique_piece_date'),
        ),
    ]
