# Generated by Django 4.2.7 on 2025-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_banque_options_alter_cotisation_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banque',
            name='banque_unique_piece_date',
        ),
        migrations.AddField(
            model_name='banque',
            name='nom_bd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='banque',
            unique_together={('N_piece', 'date_piece', 'Montant_en_devise_interne')},
        ),
    ]
