# Generated by Django 4.2.7 on 2025-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_banque_banque_unique_piece_date_banque_nom_bd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={'verbose_name': 'Opération bancaire', 'verbose_name_plural': 'Opérations bancaires'},
        ),
        migrations.AlterField(
            model_name='banque',
            name='Montant_en_devise_interne',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant en devise interne'),
        ),
        migrations.AlterField(
            model_name='banque',
            name='N_piece',
            field=models.CharField(max_length=50, verbose_name='Nº pièce'),
        ),
        migrations.AlterField(
            model_name='banque',
            name='nom_bd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom dans la base'),
        ),
    ]
