# Generated by Django 4.2.7 on 2025-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_banque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='ecart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Écart'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reste'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='type_paiement',
            field=models.CharField(choices=[('CMSS_EXACT', 'CMSS exact'), ('CMCAS_EXACT', 'CMCAS exact'), ('CMSS_CMCAS', 'CMSS + CMCAS'), ('CMSS_PROCH', 'CMSS proche'), ('CMCAS_PROCH', 'CMCAS proche'), ('INCOMPATIBLE', 'Incompatible')], default='INCOMPATIBLE', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
