# Generated by Django 4.2.7 on 2025-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_cotisation_ecart_cotisation_reste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomIncoherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('trimestre', models.CharField(choices=[('Q1', 'Janvier - Mars'), ('Q2', 'Avril - Juin'), ('Q3', 'Juillet - Septembre'), ('Q4', 'Octobre - Décembre')], max_length=2)),
                ('date_operation', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nom incohérent',
                'verbose_name_plural': 'Noms incohérents',
            },
        ),
        migrations.CreateModel(
            name='VirementManque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('num_secu', models.CharField(max_length=15, verbose_name='Numéro de sécurité sociale')),
                ('date_prevue', models.DateField()),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_retard', 'En retard'), ('non_recu', 'Non reçu'), ('partiel', 'Reçu partiellement')], default='en_retard', max_length=20)),
                ('annee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Virement manqué',
                'verbose_name_plural': 'Virements manqués',
            },
        ),
    ]
