# Generated by Django 4.2.7 on 2025-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_nomincoherent_virementmanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomincoherent',
            name='trimestre',
            field=models.CharField(choices=[('T1:Janvier', 'Janvier - Mars'), ('T2:Avril ', 'Avril - Juin'), ('T3:Juillet ', 'Juillet - Septembre'), ('T4:Octobre ', 'Octobre - Décembre')], max_length=50),
        ),
    ]
