# Generated by Django 4.2.7 on 2025-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_nomincoherent_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virementmanque',
            name='date_prevue',
        ),
        migrations.AddField(
            model_name='virementmanque',
            name='trimestre_manquant',
            field=models.CharField(choices=[('T1:Janvier', 'Janvier - Mars'), ('T2:Avril ', 'Avril - Juin'), ('T3:Juillet ', 'Juillet - Septembre'), ('T4:Octobre ', 'Octobre - Décembre')], default='INCONNU', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virementmanque',
            name='type',
            field=models.CharField(choices=[('CMSS', 'CMSS'), ('CMCAS', 'CMCAS'), ('CMSS+CMCAS', 'CMSS+CMCAS')], default='inconnu', max_length=50),
            preserve_default=False,
        ),
    ]
