# Generated by Django 4.2.7 on 2025-08-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_virementmanque_date_prevue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virementmanque',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='virementmanque',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='virementmanque',
            name='num_secu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_manques', to='gestion.retraite', verbose_name='Numéro de sécurité sociale'),
        ),
        migrations.AlterField(
            model_name='virementmanque',
            name='trimestre_manquant',
            field=models.CharField(choices=[('T1:Janvier', 'Janvier - Mars'), ('T2:Avril', 'Avril - Juin'), ('T3:Juillet', 'Juillet - Septembre'), ('T4:Octobre', 'Octobre - Décembre')], max_length=50),
        ),
    ]
