# Generated by Django 4.2.7 on 2025-08-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_virementmanque_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomincoherent',
            name='date_operation',
        ),
        migrations.RemoveField(
            model_name='nomincoherent',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='nomincoherent',
            name='nom',
        ),
        migrations.AddField(
            model_name='nomincoherent',
            name='banque',
            field=models.CharField(default='Inconnue', max_length=100, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='nomincoherent',
            name='trimestre',
            field=models.CharField(choices=[('T1:Janvier', 'Janvier - Mars'), ('T2:Avril', 'Avril - Juin'), ('T3:Juillet', 'Juillet - Septembre'), ('T4:Octobre', 'Octobre - Décembre')], max_length=50),
        ),
    ]
