# Generated by Django 4.2.7 on 2025-08-26 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_nomincoherent_date_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomincoherent',
            name='date_operation',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomincoherent',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomincoherent',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.banque', verbose_name='Opération bancaire'),
        ),
        migrations.AlterField(
            model_name='nomincoherent',
            name='trimestre',
            field=models.CharField(choices=[('T1:Janvier', 'Janvier - Mars'), ('T2:Avril ', 'Avril - Juin'), ('T3:Juillet ', 'Juillet - Septembre'), ('T4:Octobre ', 'Octobre - Décembre')], max_length=50),
        ),
    ]
