# Generated by Django 4.2.7 on 2025-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_nomincoherent_date_operation_nomincoherent_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomincoherent',
            name='banque',
        ),
        migrations.AddField(
            model_name='nomincoherent',
            name='nom',
            field=models.CharField(default='inconnu', max_length=200),
            preserve_default=False,
        ),
    ]
