# Generated by Django 4.2.7 on 2025-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_gestionnaireprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virementmanque',
            name='type',
        ),
        migrations.AddField(
            model_name='virementmanque',
            name='type_paiement',
            field=models.CharField(choices=[('CMSS_EXACT', 'CMSS exact'), ('CMCAS_EXACT', 'CMCAS exact'), ('CMSS_CMCAS', 'CMSS + CMCAS'), ('CMSS_PROCH', 'CMSS proche'), ('CMCAS_PROCH', 'CMCAS proche'), ('INCOMPATIBLE', 'Incompatible')], default='INCOMPATIBLE', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
