# Generated by Django 4.2.7 on 2025-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_virementmanque_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomincoherent',
            name='n_piece',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
